## CONFIGURATION FILE FOR CLASSIFICATION XPS SCHIZOPHRENIA - BIPOLAR

XP_NAME :
  "CLASSIF_BIP_HC"

#############################################
########### DATASET_CONFIG ##################
#############################################
DATASET_CONFIG :
  DATA_DIRS :
    ROOT : "/home/robin/Desktop/rl264746/neurospin/psy/"
    metadata_path :
      - "biobd_cat12vbm_participants.csv"
      - "bsnip1_cat12vbm_participants.csv"
    input_path :
      - "biobd_cat12vbm_rois-gs.csv"
      - "bsnip1_cat12vbm_rois-gs.csv"

  ## Number of folds / Max sample number per labels / Max train set length
  N_FOLD : 10
  N_TRAIN_MAX : 663
  N_TRAIN_MAX_PER_LABEL : ~
  TRAIN_SIZE : 0.9

  ## RESIDUALS : Regress out some metadata
  RESIDUALS : ~
  #  REGRESS_OUT : "site"
  #  WITH_RESPECT_TO : "site + age + sex + diagnosis"

  ## Features to filter out
  FEATURES_FILTER :
    KEYWORDS :
      - "participant_id"
      - "run"
      - "session"
      - "TIV"
      - "CSF_Vol"
      - "GM_Vol"
      - "WM_Vol"
    SUB_KEYWORDS :
      - "CSF_Vol"

  ## Stratification type
  STRATIFICATION : "CLASSIF_BIP_HC"

  ## String to Label conversion dict
  LABEL_DICT:
    psychotic bipolar disorder: 1
    bipolar disorder: 1
    control: 0


#############################################
########### METRICS_CONFIG ##################
#############################################
METRICS_CONFIG :
  ## Define supervised classification metrics
  CLASSIFICATION :
      metrics :
        - 'AUC'
        - 'BACC'
        - 'ACC'
      phase :
        - 'TEST'
        - 'VAL'
      hp :
        testing_label_mapping :
          0 : 0
          1 : 1


#############################################
########### ML_METHOD_CONFIG ################
#############################################
ML_METHOD_CONFIG :
  ## Define Dimensionality Reduction method (example : "PCA", "ICA")
  DR_METHOD : ~
  ## Define ML Method method (example : "HYDRA", "SVM")
  ML_METHOD :
    name : "SVM"
    hyperparameters :
      C :
        - 0.1
        - 1
      kernel :
        - 'rbf'
        - 'linear'
      probability : True
