## CONFIGURATION FILE FOR CLASSIFICATION XPS SCHIZOPHRENIA - BIPOLAR

XP_NAME :
  "CLASSIF_SKZ_BIP"

#############################################
########### DATASET_CONFIG ##################
#############################################
DATASET_CONFIG :
  DATA_DIRS :
    ROOT : "/home/robin/Desktop/rl264746/neurospin/psy/"
    metadata_path :
      - "biobd_cat12vbm_participants.csv"
      - "bsnip1_cat12vbm_participants.csv"
      - "schizconnect-vip-prague_cat12vbm_participants.csv"
      - "start-icaar-eugei_cat12vbm_participants.csv"
    input_path :
      - "biobd_cat12vbm_rois-gs.csv"
      - "bsnip1_cat12vbm_rois-gs.csv"
      - "schizconnect-vip-prague_cat12vbm_rois-gs.csv"
      - "start-icaar-eugei_cat12vbm_rois-gs.csv"

  ## Number of folds / Max sample number per labels / Max train set length
  N_FOLD : 10
  N_TRAIN_MAX : 99
  N_TRAIN_MAX_PER_LABEL : ~
  TRAIN_SIZE : 0.8

  ## RESIDUALS : Regress out some metadata
  RESIDUALS :
    REGRESS_OUT : "site + age + sex"
    WITH_RESPECT_TO : "site + age + sex + diagnosis"

  ## Features to filter out
  FEATURES_FILTER :
    KEYWORDS :
      - "participant_id"
      - "run"
      - "session"
      - "TIV"
      - "CSF_Vol"
      - "GM_Vol"
      - "WM_Vol"
    SUB_KEYWORDS :
      - "CSF_Vol"

  ## Stratification type
  STRATIFICATION : "CLASSIF_UHR"

  ## String to Label conversion dict
  LABEL_DICT:
    UHR-NC: 0
    UHR-C: 1
    schizophrenia: 2
    control: 3


#############################################
########### METRICS_CONFIG ##################
#############################################
METRICS_CONFIG :
  ## Define supervised classification metrics
  CLASSIFICATION :
      metrics :
        - 'AUC'
        - 'BACC'
        - 'ACC'
        - 'ARI'
        - 'V_measure'
      phase :
        - 'VAL'
      hp :
        testing_label_mapping :
          0 : 0
          1 : 1


#############################################
########### ML_METHOD_CONFIG ################
#############################################
ML_METHOD_CONFIG :
  ## Define Dimensionality Reduction method (example : "PCA", "ICA")
  DR_METHOD : ~
  ## Define ML Method method (example : "HYDRA", "SVM")
  ML_METHOD :
    name : "SVM"
    hyperparameters :
      probability : True
      C : 0.1
      kernel : 'rbf'

